DROP DATABASE ESCOLA_DB;
CREATE DATABASE ESCOLA_DB;
USE ESCOLA_DB;

CREATE TABLE CURS (
  ID_CURS int(15) NOT NULL AUTO_INCREMENT,
  NOM_CURS varchar(255) DEFAULT NULL,
  NOM_RESPONSABLE varchar(255) DEFAULT NULL,
  PRIMARY KEY (ID_CURS)
);

CREATE TABLE ALUMNE (
  ID_ALUMNE int(15) NOT NULL AUTO_INCREMENT,
  NOM_ALUMNE varchar(255) DEFAULT NULL,
  COGNOM1_ALUMNE varchar(255) DEFAULT NULL,
  COGNOM2_ALUMNE varchar(255) DEFAULT NULL,
  CURS_ID int(15) DEFAULT NULL,
  PRIMARY KEY (ID_ALUMNE),
  KEY CURS_ID (CURS_ID),
  CONSTRAINT ALUMNE_ibfk_1 FOREIGN KEY (CURS_ID) REFERENCES CURS (ID_CURS)
);

CREATE TABLE ASSIGNATURA (
  ID_ASSIGNATURA int(15) NOT NULL AUTO_INCREMENT,
  NOM_ASSIGNATURA varchar(255) DEFAULT NULL,
  NOM_PROFESSOR varchar(255) DEFAULT NULL,
  CURS_ID int(11) DEFAULT NULL,
  PRIMARY KEY (ID_ASSIGNATURA),
  KEY CURS_ID (CURS_ID),
  CONSTRAINT ASSIGNATURA_ibfk_1 FOREIGN KEY (CURS_ID) REFERENCES CURS (ID_CURS)
);

CREATE TABLE NOTA (
  ID_NOTA int(15) NOT NULL AUTO_INCREMENT,
  ASSIGNATURA_ID int(15) DEFAULT NULL,
  CURS_ID int(15) DEFAULT NULL,
  ALUMNE_ID int(15) DEFAULT NULL,
  NOTA int(11) DEFAULT NULL,
  UF1 int(11) DEFAULT NULL,
  UF2 int(11) DEFAULT NULL,
  UF3 int(11) DEFAULT NULL,
  UF4 int(11) DEFAULT NULL,
  PRIMARY KEY (ID_NOTA),
  KEY ASSIGNATURA_ID (ASSIGNATURA_ID),
  KEY CURS_ID (CURS_ID),
  KEY ALUMNE_ID (ALUMNE_ID),
  CONSTRAINT NOTA_ibfk_1 FOREIGN KEY (ASSIGNATURA_ID) REFERENCES ASSIGNATURA (ID_ASSIGNATURA),
  CONSTRAINT NOTA_ibfk_2 FOREIGN KEY (CURS_ID) REFERENCES CURS (ID_CURS),
  CONSTRAINT NOTA_ibfk_3 FOREIGN KEY (ALUMNE_ID) REFERENCES ALUMNE (ID_ALUMNE)
);
